### ISSUE TITLE
Cannot import Crypto module

### ISSUE THREAD

**Issue by nengha** [chrissimpkins/crypto#24]
I am using Firestore through firebase package and faced this import error whenever I run the code. 
`Traceback (most recent call last):
  File "/Users/piku/Projects/FilesBot/FileStoreBot/utils/database.py", line 1, in <module>
    from firebase import Database, Firebase
  File "/usr/local/lib/python3.9/site-packages/firebase/__init__.py", line 20, in <module>
    from crypto.PublicKey import RSA
  File "/usr/local/lib/python3.9/site-packages/crypto/PublicKey/RSA.py", line 43, in <module>
    from crypto.Math.Primality import (test_probable_prime,
  File "/usr/local/lib/python3.9/site-packages/crypto/Math/Primality.py", line 216, in <module>
    from Crypto.Util.number import sieve_base as _sieve_base_large
ModuleNotFoundError: No module named 'Crypto'`

The import looks like
`from Crypto.PublicKey import RSA`

After following up I found that changing 'from Crypto' to 'from crypto' works fine with the import. Asking if its a package bug in the crypto 1.4.1 or otherwise. 

Thank you in Advance.

**Comment by chrissimpkins** [comment]
I think that you have the wrong project.  We do not support that API.  It may be https://pypi.org/project/pycrypto/?  Sorry!
